### PR TITLE
Exceptions 0.10.0

### LINKED ISSUE #54: Fix the build and tests with exceptions 0.9.*
The builds for PRs #52 and #53 both fail with the same error:

During the build phase, there is a warning which wasn't there before, saying that the `generalBracket` method is missing from a `MonadMask` instance. Neither PR touches that part of the code, and yet [previous builds](https://travis-ci.org/mvdan/hint/jobs/334673373) don't include the warning.

This is only a warning, but alas, both warnings become errors later on, when the unit tests are executed. In fact, each test fails separately with the same error message, indicating that it must be hint which is somehow trying to load its own code and failing because of a warning.

I did write both PR #52 and PR #53, but I don't think it is my changes which have caused this. One reason is that the two PRs touch different parts of the codebase and yet fail in the same way. The other is that while PR #53 configures Travis so that it also attempts to build with ghc-8.4, it doesn't make any change which should impact the build for the other versions of ghc, and yet the build fails for those versions of ghc as well.

My conclusion is that something in the build environment must have changed between the last (successful) build and these ones.

### PR DESCRIPTION
**Pull request by gelisam**
Fixes #54

### CODE REVIEW

File: src/Control/Monad/Ghc.hs [hunk 1]
```diff
@@ -60,7 +60,20 @@ instance (MonadIO m, MonadMask m) => MonadMask (GhcT m) where
         wrap g   = GhcT $ GHC.GhcT $ \s -> MTLAdapter (g s)
         unwrap m = unMTLA . GHC.unGhcT (unGhcT m)
 
-    uninterruptibleMask = mask
+    uninterruptibleMask f = wrap $ \s ->
+                              uninterruptibleMask $ \io_restore ->
+                                unwrap (f $ \m -> (wrap $ \s' -> io_restore (unwrap m s'))) s
+      where
+        wrap g   = GhcT $ GHC.GhcT $ \s -> MTLAdapter (g s)
+        unwrap m = unMTLA . GHC.unGhcT (unGhcT m)
```
Comment (gelisam) [inline src/Control/Monad/Ghc.hs]: I also took the opportunity to fix the implementation of `uninterruptibleMask`. It was previously defined as `uninterruptibleMask = mask`, so calling `uninterruptibleMask body` was misleadingly running `body` in interruptible mode, not in uninterruptible mode. The difference is that some calls, like `threadDelay`, are intentionally marked as being interruptible even when running inside `mask`. As a result,

    > timeout 1000000 $ mask $ \_ -> threadDelay 3000000

terminates after 1 second because the timeout successfully interrupts the threadDelay after 1 second, while

    > timeout 1000000 $ uninterruptibleMask $ \_ -> lift $ threadDelay 3000000

terminates after 3 seconds, because the timeout has to wait until the `uninterruptibleMask` computation terminates before aborting the computation.

Without this fix,

    > timeout 1000000 $ runGhcT ... $ mask $ \_ -> lift $ threadDelay 3000000

and

    > timeout 1000000 $ runGhcT ... $ uninterruptibleMask $ \_ -> lift $ threadDelay 3000000

both terminate after 1 second, whereas with this fix, the second terminates after 3 seconds, as desired.

File: src/Control/Monad/Ghc.hs [hunk 2]
```diff
@@ -60,7 +60,20 @@ instance (MonadIO m, MonadMask m) => MonadMask (GhcT m) where
...
+
+    generalBracket acquire release body
+      = wrap $ \s -> generalBracket (unwrap acquire s)
+                                    (\a exitCase -> unwrap (release a exitCase) s)
+                                    (\a -> unwrap (body a) s)
+      where
+        wrap g   = GhcT $ GHC.GhcT $ \s -> MTLAdapter (g s)
+        unwrap m = unMTLA . GHC.unGhcT (unGhcT m)
```
Comment (gelisam) [inline src/Control/Monad/Ghc.hs]: This is the main fix: exceptions-0.9 introduced a new method named `generalBracket`, whose type I fixed in exceptions-0.10, so in order to upgrade from exceptions-0.8 to exceptions-0.10, we have to implement this method. If we wanted, we could add an `#ifdef` around this method definition in order to support both.

Comment (mvdan) [reply src/Control/Monad/Ghc.hs]: What about depending on exceptions >= 0.8.0?

Comment (gelisam) [reply src/Control/Monad/Ghc.hs]: Do you mean >= 0.10.0, or did you change your mind and now want an `#ifdef` in order to support both 0.8 and 0.10?

Comment (mvdan) [reply src/Control/Monad/Ghc.hs]: I indeed meant >= 0.10.0 - thanks for spotting that. I would not bother supporting 0.8 and earlier, especially given how it's a v0, and how we're likely one of the last libraries to add support for the new exceptions versions.

Comment (gelisam) [reply src/Control/Monad/Ghc.hs]: fixed, merging
